import Banner from "@/components/Home/Banner/Banner";
import BestSellerSection from "@/components/Home/Sections/BestSellerSection";
import FabricsSection from "@/components/Home/Sections/FabricsSection";
import OccassionsSection from "@/components/Home/Sections/OccassionsSection";
import SpecialCollectionsSection from "@/components/Home/Sections/SpecialCollectionsSection";
import React from "react";

interface Props {
    occasionData: any[];
    fabricsData: any[];
    collectionsData: any[];
}

const HomeCollections: React.FC<Props> = ({ collectionsData, fabricsData, occasionData }) => {
    return (
        <>
            <Banner />

            <FabricsSection fabricsData={fabricsData} />

            <hr className="lg:hidden mt-10 lg:mt-20 max-w-xs lg:max-w-screen-xl border-gray-300 mx-auto w-10/12" />

            <BestSellerSection
                bestSellerData={[
                    {
                        _id: "65e9a804c36dc4fd35013f1a",
                        name: "red pure khadi cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwa1d5e0a6/images/Taneira/Catalog/SHV06L00010_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw00dea904/images/Taneira/Catalog/SHV06L00010_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw6e2cf277/images/Taneira/Catalog/SHV06L00010_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw5ae5f56c/images/Taneira/Catalog/SHV06L00010_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 11000,
                        discount: 25,
                        stock: 0,
                        published: true,
                        createdAt: "2024-03-07T11:41:56.848Z",
                        slug: "red-pure-khadi-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0c93",
                        name: "red pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdd173c9c/images/Taneira/Catalog/SPH08A00054_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwb69f8b25/images/Taneira/Catalog/SPH08A00054_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwaa0e4bd1/images/Taneira/Catalog/SPH08A00054_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw724bd97f/images/Taneira/Catalog/SPH08A00054_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        stock: 187,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "red-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1cc8",
                        name: "brown pure cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw80bdc798/images/Taneira/Catalog/SPG06L00511_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw6025e476/images/Taneira/Catalog/SPG06L00511_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf805770a/images/Taneira/Catalog/SPG06L00511_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw529db293/images/Taneira/Catalog/SPG06L00511_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        discount: 25,
                        stock: 187,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.064Z",
                        slug: "brown-pure-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0c6b",
                        name: "red pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw2e886d50/images/Taneira/Catalog/SPH07L00053_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw68573be3/images/Taneira/Catalog/SPH07L00053_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw490dffac/images/Taneira/Catalog/SPH07L00053_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw8403ca2c/images/Taneira/Catalog/SPH07L00053_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 184,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "red-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0fb5",
                        name: "red pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw576e0d74/images/Taneira/Catalog/SPH07L00034_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwd0fae71d/images/Taneira/Catalog/SPH07L00034_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw52dbbc34/images/Taneira/Catalog/SPH07L00034_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw3629efa0/images/Taneira/Catalog/SPH07L00034_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 162,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "red-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a804c36dc4fd35013f8d",
                        name: "red pure khadi cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw39e1f44a/images/Taneira/Catalog/SHV06L00007_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw303c6040/images/Taneira/Catalog/SHV06L00007_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw58084db6/images/Taneira/Catalog/SHV06L00007_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0f335474/images/Taneira/Catalog/SHV06L00007_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 11000,
                        discount: 25,
                        stock: 160,
                        published: true,
                        createdAt: "2024-03-07T11:41:56.848Z",
                        slug: "red-pure-khadi-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0f8d",
                        name: "green pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw751681ee/images/Taneira/Catalog/SPH07L00029_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw403ea59e/images/Taneira/Catalog/SPH07L00029_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw954d697d/images/Taneira/Catalog/SPH07L00029_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw2c3b8fff/images/Taneira/Catalog/SPH07L00029_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 154,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "green-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1280",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw167058b5/images/Taneira/Catalog/SPH07L00040_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwafa36f44/images/Taneira/Catalog/SPH07L00040_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0bd89e3b/images/Taneira/Catalog/SPH07L00040_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw375589ea/images/Taneira/Catalog/SPH07L00040_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 153,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1951",
                        name: "black cotton ajrakh saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0f200cf8/images/Taneira/Catalog/SPH07L00046_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwa05b5bdd/images/Taneira/Catalog/SPH07L00046_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwa46178c1/images/Taneira/Catalog/SPH07L00046_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdee6b4a5/images/Taneira/Catalog/SPH07L00046_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        discount: 15,
                        stock: 148,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.064Z",
                        slug: "black-cotton-ajrakh-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a12a8",
                        name: "red pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw8f4b5821/images/Taneira/Catalog/SPH08A00051_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw963e1a3b/images/Taneira/Catalog/SPH08A00051_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf79855ac/images/Taneira/Catalog/SPH08A00051_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw1275139a/images/Taneira/Catalog/SPH08A00051_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        stock: 146,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "red-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1559",
                        name: "yellow pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwd6f91e53/images/Taneira/Catalog/SPH07L00057_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw76cb58cf/images/Taneira/Catalog/SPH07L00057_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw54b11f63/images/Taneira/Catalog/SPH07L00057_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwbe98cc0a/images/Taneira/Catalog/SPH07L00057_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 145,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "yellow-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0b5c",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw085077e8/images/Taneira/Catalog/SPH08A00035_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw68ab1f96/images/Taneira/Catalog/SPH08A00035_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw4bdf5807/images/Taneira/Catalog/SPH08A00035_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0e612262/images/Taneira/Catalog/SPH08A00035_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        stock: 144,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.062Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0ad1",
                        name: "green pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw26e71bc6/images/Taneira/Catalog/SPH07L00060_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwee120e1e/images/Taneira/Catalog/SPH07L00060_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw1dcff289/images/Taneira/Catalog/SPH07L00060_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwce5a0e74/images/Taneira/Catalog/SPH07L00060_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 142,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.062Z",
                        slug: "green-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1105",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw6b2194ec/images/Taneira/Catalog/SPH07L00054_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw76a70df7/images/Taneira/Catalog/SPH07L00054_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw49d30bc7/images/Taneira/Catalog/SPH07L00054_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw1326d60a/images/Taneira/Catalog/SPH07L00054_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 142,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1119",
                        name: "maroon pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw9ce80e0e/images/Taneira/Catalog/SPH07L00050_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf128522d/images/Taneira/Catalog/SPH07L00050_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw75ac1eb7/images/Taneira/Catalog/SPH07L00050_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf0b22fad/images/Taneira/Catalog/SPH07L00050_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 140,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "maroon-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0f29",
                        name: "red pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw52f1aa80/images/Taneira/Catalog/SPH08A00030_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdf0da1ba/images/Taneira/Catalog/SPH08A00030_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwbc483ce4/images/Taneira/Catalog/SPH08A00030_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw05e742c0/images/Taneira/Catalog/SPH08A00030_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        stock: 136,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "red-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1b1a",
                        name: "black pure cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwc07c96a3/images/Taneira/Catalog/SPG06L00081_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw14b639f3/images/Taneira/Catalog/SPG06L00081_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdee8d3c1/images/Taneira/Catalog/SPG06L00081_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0d65c5b0/images/Taneira/Catalog/SPG06L00081_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4250,
                        discount: 25,
                        stock: 126,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.064Z",
                        slug: "black-pure-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0bd2",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwe86367bd/images/Taneira/Catalog/SPH07L00055_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw254faf26/images/Taneira/Catalog/SPH07L00055_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwb6964c58/images/Taneira/Catalog/SPH07L00055_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw246b1b09/images/Taneira/Catalog/SPH07L00055_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 124,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a804c36dc4fd35013fa0",
                        name: "black pure khadi cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwc8ab6f85/images/Taneira/Catalog/SHV06L00003_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw6d8960e5/images/Taneira/Catalog/SHV06L00003_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw274d9bff/images/Taneira/Catalog/SHV06L00003_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdda10ce3/images/Taneira/Catalog/SHV06L00003_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 11000,
                        discount: 25,
                        stock: 105,
                        published: true,
                        createdAt: "2024-03-07T11:41:56.848Z",
                        slug: "black-pure-khadi-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a156d",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw3b62950b/images/Taneira/Catalog/SPH07L00039_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwddfea154/images/Taneira/Catalog/SPH07L00039_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwbff37628/images/Taneira/Catalog/SPH07L00039_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw54ce0a08/images/Taneira/Catalog/SPH07L00039_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 99,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1169",
                        name: "yellow pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0810627e/images/Taneira/Catalog/SPH07L00048_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw9686036a/images/Taneira/Catalog/SPH07L00048_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0265e82f/images/Taneira/Catalog/SPH07L00048_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw24f26d7a/images/Taneira/Catalog/SPH07L00048_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 86,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "yellow-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0ca7",
                        name: "yellow pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwff8e0705/images/Taneira/Catalog/SPH07L00038_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwae1c7483/images/Taneira/Catalog/SPH07L00038_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwd564187f/images/Taneira/Catalog/SPH07L00038_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw4c087255/images/Taneira/Catalog/SPH07L00038_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 73,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "yellow-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0d83",
                        name: "grey pure cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwdcc36e48/images/Taneira/Catalog/SPG06L00076_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf39ab10e/images/Taneira/Catalog/SPG06L00076_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwb4afdbbd/images/Taneira/Catalog/SPG06L00076_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw75ac4316/images/Taneira/Catalog/SPG06L00076_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4250,
                        discount: 25,
                        stock: 71,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "grey-pure-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1294",
                        name: "brown pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw2646b92b/images/Taneira/Catalog/SPH07L00033_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwec31371b/images/Taneira/Catalog/SPH07L00033_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw72373773/images/Taneira/Catalog/SPH07L00033_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw6c6b9f1f/images/Taneira/Catalog/SPH07L00033_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4999,
                        stock: 69,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "brown-pure-cotton-ajrakh-block-print-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a1382",
                        name: "black pure cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwabc78c5c/images/Taneira/Catalog/SPG06L00087_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw4d31e335/images/Taneira/Catalog/SPG06L00087_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw8cc050a1/images/Taneira/Catalog/SPG06L00087_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw2045d6b2/images/Taneira/Catalog/SPG06L00087_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 4250,
                        discount: 25,
                        stock: 57,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "black-pure-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a804c36dc4fd3501419f",
                        name: "red pure khadi cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw88492e4c/images/Taneira/Catalog/SHV06L00004_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw4513b1a9/images/Taneira/Catalog/SHV06L00004_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwa7c2566e/images/Taneira/Catalog/SHV06L00004_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw38be71d4/images/Taneira/Catalog/SHV06L00004_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 11000,
                        discount: 25,
                        stock: 42,
                        published: true,
                        createdAt: "2024-03-07T11:41:56.848Z",
                        slug: "red-pure-khadi-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a804c36dc4fd350141b2",
                        name: "black pure khadi cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw9e8853b1/images/Taneira/Catalog/SHV06L00002_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw41715a96/images/Taneira/Catalog/SHV06L00002_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwf9612eb6/images/Taneira/Catalog/SHV06L00002_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dwfef62fdb/images/Taneira/Catalog/SHV06L00002_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 11000,
                        discount: 25,
                        stock: 31,
                        published: true,
                        createdAt: "2024-03-07T11:41:56.848Z",
                        slug: "black-pure-khadi-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0edf",
                        name: "black pure cotton ajrakh printed saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw3e0f4a82/images/Taneira/Catalog/SPG06I00293_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw75ec5392/images/Taneira/Catalog/SPG06I00293_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw679794ea/images/Taneira/Catalog/SPG06I00293_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw9de91284/images/Taneira/Catalog/SPG06I00293_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3900,
                        discount: 25,
                        stock: 17,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "black-pure-cotton-ajrakh-printed-saree",
                    },
                    {
                        _id: "65e9a707d0946d23ba2a0c57",
                        name: "blue pure cotton ajrakh block print saree",
                        images: [
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw9ca495f5/images/Taneira/Catalog/SPH08A00052_1.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw57be7094/images/Taneira/Catalog/SPH08A00052_2.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw25fd12a3/images/Taneira/Catalog/Ajrakh.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw0e479bed/images/Taneira/Catalog/SPH08A00052_3.jpg?sw=1000&sh=1500",
                            "https://www.taneira.com/dw/image/v2/BKMH_PRD/on/demandware.static/-/Sites-Taneira-product-catalog/default/dw60ba0ae1/images/Taneira/Catalog/SPH08A00052_4.jpg?sw=1000&sh=1500",
                        ],
                        MRP: 3999,
                        stock: 6,
                        published: true,
                        createdAt: "2024-03-07T11:37:44.063Z",
                        slug: "blue-pure-cotton-ajrakh-block-print-saree",
                    },
                ]}
            />

            <hr className="lg:hidden mt-10 lg:mt-20 max-w-xs lg:max-w-screen-xl border-gray-300 mx-auto w-10/12" />

            <OccassionsSection occasionData={occasionData} />

            <hr className="mt-10 lg:mt-20 max-w-xs lg:max-w-screen-xl border-gray-300 mx-auto w-10/12" />

            <SpecialCollectionsSection collectionsData={collectionsData} />
        </>
    );
};

export default HomeCollections;
